import { mkdir, copyFile, writeFile } from "node:fs/promises";
import {
  loadKnownRareChars,
  loadBlockManifest,
  blockFileFor,
} from "./cjk-fallback.mjs";
await mkdir("public/vendor", { recursive: true });
await copyFile(
  "node_modules/xlsx/dist/xlsx.full.min.js",
  "public/vendor/xlsx.full.min.js",
);
await copyFile("node_modules/xlsx/LICENSE", "public/vendor/xlsx.LICENSE.txt");

// Self-hosted fallback font for decomposition components outside the BMP
// (CJK Extension B and beyond) that no system/common web CJK font covers -
// see scripts/cjk-fallback.mjs for why. Only the specific ~200KB
// unicode-range chunks the current data actually needs are vendored, not the
// whole 14MB font family.
const fontDir = "public/vendor/fonts/hanamin";
await mkdir(fontDir, { recursive: true });
const manifest = loadBlockManifest();
const files = [
  ...new Set(
    loadKnownRareChars()
      .chars.map((ch) => blockFileFor(ch, manifest))
      .filter(Boolean),
  ),
];
const faces = [];
for (const file of files) {
  await copyFile(
    `node_modules/@vp-tw/cjk-web-fonts-hanamin/dist/HanaMinB/${file}`,
    `${fontDir}/${file}`,
  );
  const ranges = manifest
    .find((b) => b.file === file)
    .ranges.map(([a, z]) => (a === z ? `U+${a.toString(16)}` : `U+${a.toString(16)}-${z.toString(16)}`))
    .join(", ");
  faces.push(
    `@font-face {\n  font-family: "CJK Fallback";\n  font-display: swap;\n  src: url("/vendor/fonts/hanamin/${file}") format("woff2");\n  unicode-range: ${ranges};\n}`,
  );
}
await copyFile(
  "node_modules/@vp-tw/cjk-web-fonts-hanamin/LICENSE.font.txt",
  `${fontDir}/LICENSE.font.txt`,
);
await writeFile(
  `${fontDir}/hanamin-fallback.css`,
  `/* Generated by scripts/vendor.mjs from scripts/data/cjk-fallback-known.json - do not edit by hand. */\n${faces.join("\n")}\n`,
);
